/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ssa.main.vista;

import javax.swing.JFrame;
import javax.swing.JRadioButton;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import ssa.main.contrl.CtrlLogin;

/**
 *
 * @author sergio
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalRegistros = new javax.swing.JTextField();
        txtRegProcesados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRegPendientes = new javax.swing.JTextField();
        pnlDatos = new javax.swing.JPanel();
        scrollTblDatos = new javax.swing.JScrollPane();
        DefaultTableModel tblDatosModel = new DefaultTableModel();
        tblDatosModel.setDataVector(null,
            new String [] {
                "Base", "Relación con registro base", "Nombre", "Ap. Paterno", "Ap. Materno",
                "CURP", "Fecha de Nacimiento", "Sexo", "Fecha de registro", "RFC"
            });
            tblDatos = new javax.swing.JTable(){
                public void tableChanged(TableModelEvent e){
                    super.tableChanged(e);
                    repaint();
                }
            };
            btnSiguiente = new javax.swing.JButton();
            btnGuardar1 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Asociación de expedientes");

            pnlInfo.setForeground(new java.awt.Color(248, 45, 13));

            jLabel1.setText("Total de Registros encontrados con posible duplicidad:");

            jLabel2.setText("Registros procesados:");

            txtTotalRegistros.setText("0");

            txtRegProcesados.setText("0");

            jLabel3.setText("Registros pendientes:");

            txtRegPendientes.setText("0");

            javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
            pnlInfo.setLayout(pnlInfoLayout);
            pnlInfoLayout.setHorizontalGroup(
                pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlInfoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInfoLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTotalRegistros))
                        .addGroup(pnlInfoLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtRegProcesados, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtRegPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            pnlInfoLayout.setVerticalGroup(
                pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlInfoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtRegProcesados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtRegPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            tblDatos.setModel(tblDatosModel);
            tblDatos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            /**
            * Tamaño de las columnas
            */
            //Columna Base
            tblDatos.getColumnModel().getColumn(0).setPreferredWidth(50);
            //Columna Relación con registro base
            tblDatos.getColumnModel().getColumn(1).setPreferredWidth(150);
            //Columna Nombre
            tblDatos.getColumnModel().getColumn(2).setPreferredWidth(100);
            //Columna Apellido Paterno
            tblDatos.getColumnModel().getColumn(3).setPreferredWidth(120);
            //Columna Apellido Materno
            tblDatos.getColumnModel().getColumn(4).setPreferredWidth(120);
            //Columna CURP
            tblDatos.getColumnModel().getColumn(5).setPreferredWidth(120);
            //Columna Fecha de nacimiento
            tblDatos.getColumnModel().getColumn(6).setPreferredWidth(100);
            //Columna Sexo
            //tblDatos.getColumnModel().getColumn(7).setPreferredWidth(50);
            //Columna Fecha de registro
            tblDatos.getColumnModel().getColumn(8).setPreferredWidth(80);
            //Columna RFC
            tblDatos.getColumnModel().getColumn(9).setPreferredWidth(120);
            /**
            * Termina tamaño de columnas
            */
            tblDatos.setColumnSelectionAllowed(true);
            tblDatos.getTableHeader().setReorderingAllowed(false);
            scrollTblDatos.setViewportView(tblDatos);
            tblDatos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

            btnSiguiente.setText("Siguiente");

            btnGuardar1.setText("Guardar y salir");

            javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
            pnlDatos.setLayout(pnlDatosLayout);
            pnlDatosLayout.setHorizontalGroup(
                pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDatosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSiguiente))
                .addGroup(pnlDatosLayout.createSequentialGroup()
                    .addComponent(scrollTblDatos)
                    .addContainerGap())
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addContainerGap(824, Short.MAX_VALUE)
                        .addComponent(btnGuardar1)
                        .addGap(133, 133, 133)))
            );
            pnlDatosLayout.setVerticalGroup(
                pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDatosLayout.createSequentialGroup()
                    .addComponent(scrollTblDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(btnSiguiente)
                    .addGap(30, 30, 30))
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                        .addContainerGap(368, Short.MAX_VALUE)
                        .addComponent(btnGuardar1)
                        .addGap(30, 30, 30)))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 205, Short.MAX_VALUE))
                        .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login login = new Login();
                login.setExtendedState(JFrame.MAXIMIZED_BOTH);
                CtrlLogin controlador = new CtrlLogin();
                
                login.setVisible(true);
                controlador.llenaCampos(tblDatos);
                //controlador.tamanioTabla(tblDatos);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JScrollPane scrollTblDatos;
    private static javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtRegPendientes;
    private javax.swing.JTextField txtRegProcesados;
    private javax.swing.JTextField txtTotalRegistros;
    // End of variables declaration//GEN-END:variables
}
